[svfmixer]
name = "SVF Mixer"

[ladder]
name = "Ladder Filter"

[dirty-biquad]
name = "Dirty Biquad"

[diodeclipper]
name = "Diode Clipper"

[saturators]
name = "Saturators"

[slew]
name = "Slew"

[wdfclipper]
name = "Diode Clipper (WDF)"
