[package]
name = "valib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
members = ["examples/svfmixer", "examples/dirty-biquad", "plugins/abrasive", "examples/diodeclipper", "xtask"]

[dependencies]
dasp_sample = "0.11.0"
nalgebra = "0.31.4"
num-traits = "0.2.15"
numeric_literals = "0.2.0"

[dev-dependencies]
csv = "1.1.6"