[package]
name = "valib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp_sample = "0.11.0"
nalgebra = "0.31.4"
num-traits = "0.2.15"
numeric_literals = "0.2.0"
