[package]
name = "valib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
members = ["examples/svfmixer", "examples/dirty-biquad", "examples/diodeclipper", "plugins/abrasive", "plugins/refuzz", "xtask"]

[workspace.package]
version = "0.1.0"
rust-version = "1.68"
authors = ["Nathan Graule <me@solarliner.dev>"]
edition = "2021"
license = "GPL-3.0-or-later"
homepage = "https://github.com/SolarLiner/valib"
repository = "https://github.com/SolarLiner/valib"
keywords = ["virtual-analog", "audio", "plugin", "va-modeling", "dsp"]

[workspace.dependencies]
nih_plug = { git = "https://github.com/geom3trik/nih-plug.git", branch = "vizia-update" }
nih_plug_vizia = { git = "https://github.com/geom3trik/nih-plug.git", branch = "vizia-update" }


[dependencies]
az = "1.2.1"
nalgebra = "0.32.3"
num-traits = "0.2.17"
numeric_literals = "0.2.0"
simba = { version = "0.8.1", features = ["wide"] }

[dev-dependencies]
csv = "1.3.0"

[features]
unstable-wdf = []

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true