extend = "./Makefile.crates.toml"

[tasks.xtask-build]
command = "cargo"
args = ["build", "-p", "xtask", "--release"]

[tasks.bundle]
dependencies = ["xtask-build"]
command = "cargo"
args = ["xtask", "bundle", "${CARGO_MAKE_CRATE_NAME}", "${@}"]

[tasks.install-target-x86_64-darwin]
command = "rustup"
args = ["target", "add", "x86_64-apple-darwin"]

[tasks.bundle-universal]
dependencies = ["xtask-build", "install-target-x86_64-darwin"]
command = "cargo"
args = ["xtask", "bundle-universal", "${CARGO_MAKE_CRATE_NAME}", "${@}"]

[tasks.build]
clear = true
dependencies = ["pre-build"]
run_task = [
    { name = "bundle-universal", condition = { platforms = ["mac"] } },
    { name = "bundle" }
]